### PR TITLE
/run is the more up-to-date place for pidfiles.

### PR DESCRIPTION
**Pull request by xnox**

### CODE REVIEW

**Comment by keybuk** [comment]
Since that's defined by an init system that doesn't use libnih, /var/run seems just fine

**Comment by vorlonofportland** [comment]
/var/run has always been an awkward choice of location; Fedora, Ubuntu, and Debian have all migrated to /run, independent of init system.

**Comment by keybuk** [comment]
The FHS still specifies /var/run - if the distributions would like to update that, that's there business - until they do, they can patch it :p

**Comment by vorlonofportland** [comment]
On Fri, Dec 06, 2013 at 04:47:34PM -0800, Scott James Remnant wrote:

> The FHS still specifies /var/run

Yes, because there is no longer a functioning forum in which to discuss
fixes to the FHS.  As soon as I can figure out how to resolve that, /var/run
-> /run is at the top of my list.

> - if the distributions would like to update that, that's there business -
>   until they do, they can patch it :p

Fair enough. :)

**Pull request closed without merging**
